#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <stdio.h>
#include <malloc.h>
#include <dmaKit.h>
#include <gsKit.h>
#include <gsToolkit.h>
#include <gsFontM.h>
#include <libpad.h>
#include <libmc.h>
#include <timer.h>
#include <unistd.h>
#include <sbv_patches.h>

#include "runner.h"
#include "runner_keyboard.h"
#include "vm.h"
#include "../data_win.h"
#include "../json_reader.h"
#include "ps2_file_system.h"
#include "ps2_audio_system.h"
#include "gs_renderer.h"
#include "ps2_utils.h"
#include "utils.h"

// Embedded ps2sdk IRX modules (generated by bin2c at build time)
extern unsigned char sio2man_irx[];
extern unsigned int size_sio2man_irx;
extern unsigned char mcman_irx[];
extern unsigned int size_mcman_irx;
extern unsigned char mcserv_irx[];
extern unsigned int size_mcserv_irx;
extern unsigned char padman_irx[];
extern unsigned int size_padman_irx;
extern unsigned char freesd_irx[];
extern unsigned int size_freesd_irx;
extern unsigned char audsrv_irx[];
extern unsigned int size_audsrv_irx;

// The maximum memory of a normal PS2 console
// Developer consoles may have more memory, but because ps2sdk does not have a way to know
// how much memory the console really has, we will use this value instead
static int MAX_MEMORY_BYTES = 33554432;

// 256-byte aligned buffer for libpad
static char padBuf[256] __attribute__((aligned(64)));

// Controller button to GML key mapping
typedef struct {
    uint16_t padButton;
    int32_t gmlKey;
} PadMapping;

static PadMapping* padMappings = nullptr;
static int padMappingCount = 0;

// Previous frame's button state for detecting press/release edges
static uint16_t prevButtons = 0xFFFF; // All buttons released (buttons are active-low)

// ===[ Loading Screen ]===

// Maximum number of chunk stats we track (24 chunks in data.win, but only some have interesting counts)
#define MAX_CHUNK_STATS 24

typedef struct {
    char label[16];
    uint32_t count;
} ChunkStat;

typedef struct {
    GSGLOBAL* gsGlobal;
    GSFONTM* gsFontM;
    ChunkStat stats[MAX_CHUNK_STATS];
    int statCount;
} LoadingScreenState;

// Draws the bottom-left credits text (shared between status screen and loading screen)
static void drawCreditsText(GSGLOBAL* gs, GSFONTM* fontm) {
    u64 darkGray = GS_SETREG_RGBAQ(0x70, 0x70, 0x70, 0x80, 0x00);
    float creditsScale = 0.4f;
    float lineHeight = 26.0f * creditsScale;
    float creditsY = 448.0f - 10.0f - lineHeight * 2.0f;

    char versionText[128];
    snprintf(versionText, sizeof(versionText), "Butterscotch (%s) [%s]", BUTTERSCOTCH_COMMIT_HASH, BUTTERSCOTCH_COMMIT_DATE);
    gsKit_fontm_print_scaled(gs, fontm, 10.0f, creditsY, 1, creditsScale, darkGray, versionText);
    gsKit_fontm_print_scaled(gs, fontm, 10.0f, creditsY + lineHeight, 1, creditsScale, darkGray, "Created by MrPowerGamerBR (https://mrpowergamerbr.com/)");
}

// Draws a simple status screen with "Butterscotch" title, optional game name, and a status message (no progress bar)
// gameName can be nullptr if the game name is not yet known
// Begins a status screen: clears, draws title + optional game name, leaves center align active
static void beginStatusScreen(GSGLOBAL* gs, GSFONTM* fontm, const char* gameName) {
    gsKit_clear(gs, GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x80, 0x00));

    u64 title = GS_SETREG_RGBAQ(0x5E, 0x54, 0x92, 0x80, 0x00);
    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);

    fontm->Align = GSKIT_FALIGN_CENTER;
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, 180.0f, 1, 0.8f, title, "Butterscotch");
    if (gameName) {
        gsKit_fontm_print_scaled(gs, fontm, 320.0f, 210.0f, 1, 0.5f, gray, gameName);
    }
}

// Ends a status screen: draws credits, resets align, flips
static void endStatusScreen(GSGLOBAL* gs, GSFONTM* fontm) {
    fontm->Align = GSKIT_FALIGN_LEFT;
    drawCreditsText(gs, fontm);
    gsKit_queue_exec(gs);
    gsKit_sync_flip(gs);
}

// Draws chunk item counts in the top-left corner (if any stats have been recorded)
static void drawChunkStats(GSGLOBAL* gs, GSFONTM* fontm, LoadingScreenState* loadingState) {
    if (!loadingState || loadingState->statCount == 0)
        return;

    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);
    fontm->Align = GSKIT_FALIGN_LEFT;
    float statsY = 10.0f;
    float statsScale = 0.35f;
    float statsLineHeight = 14.0f;
    char statLine[32];

    repeat(loadingState->statCount, i) {
        snprintf(statLine, sizeof(statLine), "%d %s", loadingState->stats[i].count, loadingState->stats[i].label);
        gsKit_fontm_print_scaled(gs, fontm, 10.0f, statsY, 1, statsScale, gray, statLine);
        statsY += statsLineHeight;
    }
}

static void drawStatusScreen(GSGLOBAL* gs, GSFONTM* fontm, const char* gameName, const char* statusText, LoadingScreenState* loadingState) {
    beginStatusScreen(gs, fontm, gameName);
    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, 300.0f, 1, 0.5f, gray, statusText);
    drawChunkStats(gs, fontm, loadingState);
    endStatusScreen(gs, fontm);
}

static void loadingScreenCallback(const char* chunkName, int chunkIndex, int totalChunks, DataWin* dataWin, void* userData) {
    LoadingScreenState* state = (LoadingScreenState*) userData;
    GSGLOBAL* gs = state->gsGlobal;
    GSFONTM* fontm = state->gsFontM;

    const char* gameName = dataWin->gen8.displayName ? dataWin->gen8.displayName : "Unknown Game";
    beginStatusScreen(gs, fontm, gameName);

    // Loading bar
    u64 white = GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00);
    u64 barBg = GS_SETREG_RGBAQ(0x40, 0x40, 0x40, 0x80, 0x00);
    u64 barFg = GS_SETREG_RGBAQ(0xFF, 0xCC, 0x00, 0x80, 0x00); // Butterscotch yellow

    float barX = 120.0f;
    float barY = 300.0f;
    float barW = 400.0f;
    float barH = 20.0f;
    float progress = (float) (chunkIndex + 1) / (float) totalChunks;

    // Bar background (dark gray)
    gsKit_prim_sprite(gs, barX, barY, barX + barW, barY + barH, 1, barBg);

    // Bar fill (butterscotch yellow)
    float fillW = barW * progress;
    if (fillW > 1.0f) {
        gsKit_prim_sprite(gs, barX, barY, barX + fillW, barY + barH, 1, barFg);
    }

    // Enable alpha blending so the font text doesn't have a black box behind it
    gs->PrimAlphaEnable = GS_SETTING_ON;
    gsKit_set_primalpha(gs, GS_SETREG_ALPHA(0, 1, 0, 1, 0), 0);

    // Percentage text centered on the bar
    char percentText[8];
    snprintf(percentText, sizeof(percentText), "%d%%", (int) (progress * 100));
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, barY + 4.5f, 1, 0.4f, white, percentText);

    // Chunk name text below the bar
    char statusText[32];
    snprintf(statusText, sizeof(statusText), "Loading %.4s... (%d/%d)", chunkName, chunkIndex + 1, totalChunks);
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, barY + barH + 10.0f, 1, 0.5f, white, statusText);

    // Memory usage below the status text
    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);
    void* heapTop = sbrk(0);
    int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
    char memText[48];
    snprintf(memText, sizeof(memText), "Memory: %.1f/%.1f MB", usedBytes / (1024.0f * 1024.0f), MAX_MEMORY_BYTES / (1024.0f * 1024.0f));
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, barY + barH + 30.0f, 1, 0.4f, gray, memText);

    // Record item counts for already-parsed chunks (callback fires before parsing, so we scan all counts each time and add any newly non-zero ones in the order they appear)
    typedef struct { uint32_t* countPtr; const char* label; } CountSource;
    CountSource sources[] = {
        { &dataWin->sond.count, "sounds" },
        { &dataWin->sprt.count, "sprites" },
        { &dataWin->bgnd.count, "backgrounds" },
        { &dataWin->font.count, "fonts" },
        { &dataWin->objt.count, "objects" },
        { &dataWin->room.count, "rooms" },
        { &dataWin->code.count, "code entries" },
        { &dataWin->txtr.count, "textures" },
    };

    // sizeof(sources) = size of the ENTIRE array
    // So, if we divide the size of the ENTIRE array by the size of a SINGLE entry, we get the number of entries
    int arrayLength = sizeof(sources) / sizeof(CountSource);

    repeat(arrayLength, i) {
        if (*sources[i].countPtr == 0)
            continue;

        // Check if we already recorded this label
        bool found = false;
        forEach(CountSource, stat, sources, state->statCount) {
            if (strcmp(stat->label, sources[i].label) == 0) {
                found = true;
                break;
            }
        }

        if (!found && MAX_CHUNK_STATS > state->statCount) {
            ChunkStat* stat = &state->stats[state->statCount++];
            snprintf(stat->label, sizeof(stat->label), "%s", sources[i].label);
            stat->count = *sources[i].countPtr;
        }
    }

    drawChunkStats(gs, fontm, state);

    gs->PrimAlphaEnable = GS_SETTING_OFF;

    endStatusScreen(gs, fontm);
}

int main(int argc, char* argv[]) {
    SifInitRpc(0);
    sbv_patch_enable_lmb();

    PS2Utils_extractDeviceKey(argv[0]);

    fprintf(stderr, "argv0 is %s, device key is %s\n", argv[0], deviceKey.key);

    PS2Utils_loadFSDrivers();

    fprintf(stderr, "Loaded FS drivers!\n");

    const char* dataWinPath = PS2Utils_createDevicePath("DATA.WIN");

    printf("Butterscotch PS2 - Loading %s\n", dataWinPath);

    // ===[ Initialize gsKit ]===
    // This must happen first so we can show the loading screen during other init steps
    GSGLOBAL* gsGlobal = gsKit_init_global();
    gsGlobal->Mode = GS_MODE_NTSC;
    gsGlobal->Interlace = GS_INTERLACED;
    gsGlobal->Field = GS_FIELD;
    gsGlobal->Width = 640;
    gsGlobal->Height = 448;
    gsGlobal->PSM = GS_PSM_CT16;
    gsGlobal->PSMZ = GS_PSMZ_16;
    gsGlobal->DoubleBuffering = GS_SETTING_ON;
    gsGlobal->ZBuffering = GS_SETTING_OFF;

    gsGlobal->PrimAAEnable = GS_SETTING_OFF;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC, D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gsKit_init_screen(gsGlobal);
    // Use ONE SHOT mode
    gsKit_mode_switch(gsGlobal, GS_ONESHOT);

    // ===[ Initialize FONTM (ROM font) for debug overlay ]===
    GSFONTM* gsFontM = gsKit_init_fontm();
    gsKit_fontm_upload(gsGlobal, gsFontM);
    gsFontM->Spacing = 0.95f;

    // ===[ Initialize Controller ]===
    drawStatusScreen(gsGlobal, gsFontM, nullptr, "Initializing controller...", nullptr);

    int ret;
    ret = SifExecModuleBuffer(sio2man_irx, size_sio2man_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load sio2man: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(mcman_irx, size_mcman_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load mcman: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(mcserv_irx, size_mcserv_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load mcserv: %d\n", ret);
        return 1;
    }
    ret = mcInit(MC_TYPE_MC);
    if (0 > ret) {
        printf("Failed to init libmc: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(padman_irx, size_padman_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load padman: %d\n", ret);
        return 1;
    }

    padInit(0);
    padPortOpen(0, 0, padBuf);

    // ===[ Load Audio IOP Modules ]===
    ret = SifExecModuleBuffer(freesd_irx, size_freesd_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load freesd: %d\n", ret);
    }
    ret = SifExecModuleBuffer(audsrv_irx, size_audsrv_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load audsrv: %d\n", ret);
    }

    // Wait for pad to be ready
    drawStatusScreen(gsGlobal, gsFontM, nullptr, "Waiting for controller...", nullptr);

    int padState;
    do {
        padState = padGetState(0, 0);
    } while (PAD_STATE_STABLE != padState && PAD_STATE_FINDCTP1 != padState);

    printf("Controller initialized\n");

    // ===[ Loading Screen State ]===
    LoadingScreenState loadingState = {
        .gsGlobal = gsGlobal,
        .gsFontM = gsFontM,
    };

    // ===[ Parse data.win ]===
    drawStatusScreen(gsGlobal, gsFontM, nullptr, "Loading data.win...", nullptr);

    DataWin* dataWin = DataWin_parse(
        dataWinPath,
        (DataWinParserOptions) {
            .parseGen8 = true,
            .parseOptn = true,
            .parseLang = true,
            .parseExtn = true,
            .parseSond = true,
            .parseAgrp = true,
            .parseSprt = true,
            .parseBgnd = true,
            .parsePath = true,
            .parseScpt = true,
            .parseGlob = true,
            .parseShdr = true,
            .parseFont = true,
            .parseTmln = true,
            .parseObjt = true,
            .parseRoom = true,
            .parseTpag = true,
            .parseCode = true,
            .parseVari = true,
            .parseFunc = true,
            .parseStrg = true,
            .parseTxtr = false,
            .parseAudo = false,
            .skipLoadingPreciseMasksForNonPreciseSprites = true,
            .progressCallback = loadingScreenCallback,
            .progressCallbackUserData = &loadingState,
        }
    );
    free(dataWinPath);

    {
        void* heapTop = sbrk(0);
        int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
        int32_t freeBytes = MAX_MEMORY_BYTES - usedBytes;
        printf("Memory after data.win parsing: used=%d bytes (%.1f KB), total=%d bytes (%.1f KB), free=%d bytes (%.1f KB)\n", usedBytes, usedBytes / 1024.0f, MAX_MEMORY_BYTES, MAX_MEMORY_BYTES / 1024.0f, freeBytes, freeBytes / 1024.0f);
    }
    // ===[ Create texture cache and renderer ]===
    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Creating renderer...", &loadingState);

    Renderer* renderer = GsRenderer_create(gsGlobal);

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Creating VM and runner...", &loadingState);

    // ===[ Load CONFIG.JSN ]===
    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Loading CONFIG.JSN...", &loadingState);

    char* configJsonPath = PS2Utils_createDevicePath("CONFIG.JSN");
    FILE* configFile = fopen(configJsonPath, "rb");
    JsonValue* configRoot = nullptr;

    if (configFile != nullptr) {
        fseek(configFile, 0, SEEK_END);
        long configSize = ftell(configFile);
        fseek(configFile, 0, SEEK_SET);

        char* configJsonText = safeMalloc((size_t) configSize + 1);
        size_t configBytesRead = fread(configJsonText, 1, (size_t) configSize, configFile);
        configJsonText[configBytesRead] = '\0';
        fclose(configFile);

        configRoot = JsonReader_parse(configJsonText);
        free(configJsonText);
    }
    free(configJsonPath);

    if (configRoot == nullptr) {
        drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "CONFIG.JSN invalid or not found!", &loadingState);
        while (true) {}
    }

    FileSystem* fileSystem = Ps2FileSystem_create(configRoot, dataWin->gen8.displayName);
    if (fileSystem == nullptr) {
        drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "CONFIG.JSN is missing the fileSystem configuration!", &loadingState);
        while (true) {}
    }

    VMContext* vm = VM_create(dataWin);
    Runner* runner = Runner_create(dataWin, vm, fileSystem);

    // Parse disabledObjects from CONFIG.JSN
    JsonValue* disabledObjectsArr = JsonReader_getObject(configRoot, "disabledObjects");
    if (disabledObjectsArr != nullptr && JsonReader_isArray(disabledObjectsArr)) {
        sh_new_strdup(runner->disabledObjects);
        int disabledCount = JsonReader_arrayLength(disabledObjectsArr);
        repeat(disabledCount, i) {
            JsonValue* elem = JsonReader_getArrayElement(disabledObjectsArr, i);
            if (elem != nullptr && JsonReader_isString(elem)) {
                const char* objName = JsonReader_getString(elem);
                shput(runner->disabledObjects, objName, 1);
                printf("Disabled object: %s\n", objName);
            }
        }
    }

    // Parse deferDrawToAfterAllSteps from CONFIG.JSN
    // When true, Runner_draw runs once after all catch-up Runner_step calls (old behavior) instead of running immediately after each Runner_step (new behavior)
    bool deferDrawToAfterAllSteps = false;
    JsonValue* deferDrawVal = JsonReader_getObject(configRoot, "deferDrawToAfterAllSteps");
    if (deferDrawVal != nullptr) {
        deferDrawToAfterAllSteps = JsonReader_getBool(deferDrawVal);
        if (deferDrawToAfterAllSteps) {
            printf("CONFIG.JSN: deferDrawToAfterAllSteps = true (draw once after all steps)\n");
        }
    }

    // Parse controllerMappings from CONFIG.JSN
    JsonValue* controllerMappingsObj = JsonReader_getObject(configRoot, "controllerMappings");
    if (controllerMappingsObj != nullptr && JsonReader_isObject(controllerMappingsObj)) {
        padMappingCount = JsonReader_objectLength(controllerMappingsObj);
        padMappings = safeMalloc(sizeof(PadMapping) * padMappingCount);
        repeat(padMappingCount, i) {
            const char* padButtonStr = JsonReader_getObjectKey(controllerMappingsObj, i);
            JsonValue* gmlKeyVal = JsonReader_getObjectValue(controllerMappingsObj, i);
            padMappings[i].padButton = (uint16_t) atoi(padButtonStr);
            padMappings[i].gmlKey = (int32_t) JsonReader_getInt(gmlKeyVal);
            printf("CONFIG.JSN: controllerMapping pad=%d -> gmlKey=%d\n", padMappings[i].padButton, padMappings[i].gmlKey);
        }
    }

    {
        void* heapTop = sbrk(0);
        int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
        int32_t freeBytes = MAX_MEMORY_BYTES - usedBytes;
        printf("Memory after VM and runner creation: used=%d bytes (%.1f KB), total=%d bytes (%.1f KB), free=%d bytes (%.1f KB)\n", usedBytes, usedBytes / 1024.0f, MAX_MEMORY_BYTES, MAX_MEMORY_BYTES / 1024.0f, freeBytes, freeBytes / 1024.0f);
    }

    runner->renderer = renderer;

    // ===[ Initialize Audio System ]===
    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Initializing audio...", &loadingState);
    Ps2AudioSystem* ps2Audio = Ps2AudioSystem_create();
    AudioSystem* audioSystem = (AudioSystem*) ps2Audio;
    audioSystem->vtable->init(audioSystem, dataWin, fileSystem);
    runner->audioSystem = audioSystem;

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Initializing renderer...", &loadingState);
    renderer->vtable->init(renderer, dataWin);

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Initializing first room...", &loadingState);
    Runner_initFirstRoom(runner);

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Reticulating splines...", &loadingState);

    Gen8* gen8 = &dataWin->gen8;
    int32_t gameW = (int32_t) gen8->defaultWindowWidth;
    int32_t gameH = (int32_t) gen8->defaultWindowHeight;

    // ===[ Initialize Timer ]===
    InitTimer(kBUSCLK);
    StartTimerSystemTime();

    // ===[ Main Loop ]===
    float lastFrameTimeMs = 0.0f;
    u64 lastVsyncTime = GetTimerSystemTime();
    double accumulator = 0.0; // seconds of game time accumulated
    bool debugOverlayEnabled = JsonReader_getBool(JsonReader_getObject(configRoot, "debugOverlayEnabled"));

    // FPS tracking: count rendered frames (screen flips) over a 1-second window
    int renderFpsCounter = 0;
    int displayedRenderFps = 0;
    u64 fpsTimerStart = GetTimerSystemTime();

    while (!runner->shouldExit) {
        u64 frameStartTime = GetTimerSystemTime();

        // Calculate delta time since last vsync
        double deltaTime = (double) (frameStartTime - lastVsyncTime) / (double) kBUSCLK;
        lastVsyncTime = frameStartTime;

        // ===[ Poll Controller (always poll every vsync) ]===
        // NOTE: We do NOT call RunnerKeyboard_beginFrame here! Pressed/released edges accumulate across vsyncs so that quick taps on non-game-frame
        // vsyncs are not lost
        //
        // beginFrame is called after the game consumes input.

        struct padButtonStatus padStatus;
        unsigned char padResult = padRead(0, 0, &padStatus);
        uint16_t buttons = 0xFFFF; // all released by default
        if (padResult != 0) {
            buttons = padStatus.btns;

            repeat(padMappingCount, i) {
                uint16_t mask = padMappings[i].padButton;
                int32_t gmlKey = padMappings[i].gmlKey;

                // PS2 buttons are active-low: 0 = pressed, 1 = released
                bool wasPressed = (prevButtons & mask) == 0;
                bool isPressed = (buttons & mask) == 0;

                if (isPressed && !wasPressed) {
                    RunnerKeyboard_onKeyDown(runner->keyboard, gmlKey);
                } else if (!isPressed && wasPressed) {
                    RunnerKeyboard_onKeyUp(runner->keyboard, gmlKey);
                }
            }

            prevButtons = buttons;
        }

        // R2 removes speed cap (run at full vsync rate)
        bool speedCapRemoved = (padResult != 0) && ((buttons & PAD_R2) == 0);

        // Go to next room
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_PAGEUP)) {
            DataWin* dw = runner->dataWin;
            if ((int32_t) dw->gen8.roomOrderCount > runner->currentRoomOrderPosition + 1) {
                int32_t nextIdx = dw->gen8.roomOrder[runner->currentRoomOrderPosition + 1];
                runner->pendingRoom = nextIdx;
                fprintf(stderr, "Debug: Going to next room -> %s\n", dw->room.rooms[nextIdx].name);
            }
        }

        // Go to previous room
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_PAGEDOWN)) {
            DataWin* dw = runner->dataWin;
            forEachIndexed(Room, room, i, dw->room.rooms, dw->room.count) {
                if (strcmp(room->name, "room_asrielappears") == 0) {
                    runner->pendingRoom = i;
                    break;
                }
            }
        }

        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_F12)) {
            debugOverlayEnabled = !debugOverlayEnabled;
        }

        // Reset global interact state because I HATE when I get stuck while moving through rooms
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_F10)) {
            int32_t interactVarId = shget(runner->vmContext->globalVarNameMap, "interact");

            runner->vmContext->globalVars[interactVarId] = RValue_makeInt32(0);
            printf("Changed global.interact [%d] value!\n", interactVarId);
        }

        // ===[ Game Logic (accumulator-based frame pacing) ]===
        uint32_t roomSpeed = runner->currentRoom->speed;
        // TODO: In the future, we'll need to check if roomSpeed == 0 and, if it is, use the game's default FPS for GameMaker: Studio 2+ games!
        double targetFrameTime = (roomSpeed > 0) ? (1.0 / roomSpeed) : (1.0 / 60.0);

        accumulator += deltaTime;

        // Cap accumulator to prevent spiral of death (max 4 game frames per vsync)
        double maxAccumulator = targetFrameTime * 4.0;
        if (accumulator > maxAccumulator) {
            accumulator = maxAccumulator;
        }

        // If R2 is held, force at least one game frame per vsync
        if (speedCapRemoved) {
            if (targetFrameTime > accumulator) {
                accumulator = targetFrameTime;
            }
        }

        int gameFramesRan = 0;
        while (accumulator >= targetFrameTime) {
            // Clear pressed/released before 2nd+ steps so press events don't fire multiple times when catching up
            if (gameFramesRan > 0)
                RunnerKeyboard_beginFrame(runner->keyboard);

            Runner_step(runner);

            if (!deferDrawToAfterAllSteps) {
                gsKit_clear(gsGlobal, GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x80, 0x00));

                renderer->vtable->beginFrame(renderer, gameW, gameH, 640, 448);

                // Clear with room background color
                if (runner->drawBackgroundColor) {
                    uint8_t bgR = BGR_R(runner->backgroundColor);
                    uint8_t bgG = BGR_G(runner->backgroundColor);
                    uint8_t bgB = BGR_B(runner->backgroundColor);
                    u64 bgColor = GS_SETREG_RGBAQ(bgR, bgG, bgB, 0x80, 0x00);
                    gsKit_prim_sprite(gsGlobal, 0, 0, 640, 448, 0, bgColor);
                }

                // Render views
                Room* activeRoom = runner->currentRoom;
                bool anyViewRendered = false;

                bool viewsEnabled = (activeRoom->flags & 1) != 0;

                if (viewsEnabled) {
                    repeat(8, vi) {
                        if (!activeRoom->views[vi].enabled) continue;

                        int32_t viewX = activeRoom->views[vi].viewX;
                        int32_t viewY = activeRoom->views[vi].viewY;
                        int32_t viewW = activeRoom->views[vi].viewWidth;
                        int32_t viewH = activeRoom->views[vi].viewHeight;
                        int32_t portX = activeRoom->views[vi].portX;
                        int32_t portY = activeRoom->views[vi].portY;
                        int32_t portW = activeRoom->views[vi].portWidth;
                        int32_t portH = activeRoom->views[vi].portHeight;
                        float viewAngle = runner->viewAngles[vi];

                        runner->viewCurrent = (int32_t) vi;
                        renderer->vtable->beginView(renderer, viewX, viewY, viewW, viewH, portX, portY, portW, portH, viewAngle);

                        Runner_draw(runner);

                        renderer->vtable->endView(renderer);
                        anyViewRendered = true;
                    }
                }

                if (!anyViewRendered) {
                    // No views enabled: render with default full-screen view
                    runner->viewCurrent = 0;
                    renderer->vtable->beginView(renderer, 0, 0, gameW, gameH, 0, 0, gameW, gameH, 0.0f);
                    Runner_draw(runner);
                    renderer->vtable->endView(renderer);
                }

                runner->viewCurrent = 0;

                renderer->vtable->endFrame(renderer);
            }

            accumulator -= targetFrameTime;
            gameFramesRan++;

            // For intermediate catch-up frames, flush the GS queue so it doesn't accumulate
            // (the back buffer will be overwritten by the next iteration's rendering anyway)
            if (!deferDrawToAfterAllSteps && accumulator >= targetFrameTime) {
                gsKit_queue_exec(gsGlobal);
            }
        }

        // When deferDrawToAfterAllSteps is enabled, render once after all catch-up steps
        if (deferDrawToAfterAllSteps && gameFramesRan > 0) {
            gsKit_clear(gsGlobal, GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x80, 0x00));

            renderer->vtable->beginFrame(renderer, gameW, gameH, 640, 448);

            // Clear with room background color
            if (runner->drawBackgroundColor) {
                uint8_t bgR = BGR_R(runner->backgroundColor);
                uint8_t bgG = BGR_G(runner->backgroundColor);
                uint8_t bgB = BGR_B(runner->backgroundColor);
                u64 bgColor = GS_SETREG_RGBAQ(bgR, bgG, bgB, 0x80, 0x00);
                gsKit_prim_sprite(gsGlobal, 0, 0, 640, 448, 0, bgColor);
            }

            // Render views
            Room* activeRoom = runner->currentRoom;
            bool anyViewRendered = false;

            bool viewsEnabled = (activeRoom->flags & 1) != 0;

            if (viewsEnabled) {
                repeat(8, vi) {
                    if (!activeRoom->views[vi].enabled) continue;

                    int32_t viewX = activeRoom->views[vi].viewX;
                    int32_t viewY = activeRoom->views[vi].viewY;
                    int32_t viewW = activeRoom->views[vi].viewWidth;
                    int32_t viewH = activeRoom->views[vi].viewHeight;
                    int32_t portX = activeRoom->views[vi].portX;
                    int32_t portY = activeRoom->views[vi].portY;
                    int32_t portW = activeRoom->views[vi].portWidth;
                    int32_t portH = activeRoom->views[vi].portHeight;
                    float viewAngle = runner->viewAngles[vi];

                    runner->viewCurrent = (int32_t) vi;
                    renderer->vtable->beginView(renderer, viewX, viewY, viewW, viewH, portX, portY, portW, portH, viewAngle);

                    Runner_draw(runner);

                    renderer->vtable->endView(renderer);
                    anyViewRendered = true;
                }
            }

            if (!anyViewRendered) {
                // No views enabled: render with default full-screen view
                runner->viewCurrent = 0;
                renderer->vtable->beginView(renderer, 0, 0, gameW, gameH, 0, 0, gameW, gameH, 0.0f);
                Runner_draw(runner);
                renderer->vtable->endView(renderer);
            }

            runner->viewCurrent = 0;

            renderer->vtable->endFrame(renderer);
        }

        // Update audio system (gain fading, stream to audsrv)
        if (runner->audioSystem != nullptr) {
            float dt = (float) deltaTime;
            if (0.0f > dt) dt = 0.0f;
            if (dt > 0.1f) dt = 0.1f;
            runner->audioSystem->vtable->update(runner->audioSystem, dt);
        }

        // Update FPS counter (counts actual rendered frames, not game logic steps)
        if (gameFramesRan > 0) {
            renderFpsCounter++;
        }
        u64 fpsElapsed = frameStartTime - fpsTimerStart;
        if (fpsElapsed >= (u64) kBUSCLK) {
            displayedRenderFps = renderFpsCounter;
            renderFpsCounter = 0;
            fpsTimerStart = frameStartTime;
        }

        if (gameFramesRan > 0) {
            // Measure frame time BEFORE flipping
            u64 frameEndTime = GetTimerSystemTime();
            lastFrameTimeMs = (float) (frameEndTime - frameStartTime) / (float) (kBUSCLK / 1000);

            // ===[ Debug Overlay ]===
            if (debugOverlayEnabled) {
                u64 debugColor = GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00);
                // sbrk(0) returns the actual heap frontier; true free = top of RAM - sbrk frontier
                void* heapTop = sbrk(0);
                int32_t freeBytes = MAX_MEMORY_BYTES - (int32_t) (uintptr_t) heapTop;

                char debugText[256];
                uint32_t vramFreeBytes = GS_VRAM_SIZE - gsGlobal->CurrentPointer;

                // Count atlases loaded in VRAM and EE RAM cache
                GsRenderer* gsRenderer = (GsRenderer*) renderer;
                uint32_t vramAtlasCount = 0;
                uint32_t eeramAtlasCount = 0;
                repeat(gsRenderer->atlasCount, ai) {
                    if (gsRenderer->atlasToChunk[ai] >= 0) vramAtlasCount++;
                    if (gsRenderer->eeCacheEntries[ai].atlasId >= 0) eeramAtlasCount++;
                }

                snprintf(debugText, sizeof(debugText), "FPS: %d\nTick: %.2fms\nFree: %d bytes\nVRAM Free: %lu bytes\nRoom Speed: %u%s\nAtlas: (%u, %u, %u)", displayedRenderFps, lastFrameTimeMs, freeBytes, (unsigned long) vramFreeBytes, roomSpeed, speedCapRemoved ? " [UNCAPPED]" : "", vramAtlasCount, eeramAtlasCount, gsRenderer->atlasCount);
                gsKit_fontm_print_scaled(gsGlobal, gsFontM, 10.0f, 10.0f, 10, 0.6f, debugColor, debugText);
            }

            // Clear accumulated input after both Step and Draw events have consumed it, so edges don't re-fire on the next game frame
            // This MUST be after Runner_draw because games CAN handle input in Draw events (example: Undertale's naming screen)
            RunnerKeyboard_beginFrame(runner->keyboard);

            // Execute draw queue and flip buffers
            gsKit_queue_exec(gsGlobal);
            gsKit_sync_flip(gsGlobal);
        } else {
            // No game frame ran, just wait for vsync without flipping
            // (flipping would show the other buffer which has stale/black content)
            gsKit_vsync_wait();
        }
    }

    if (runner->audioSystem != nullptr) {
        runner->audioSystem->vtable->destroy(runner->audioSystem);
        runner->audioSystem = nullptr;
    }
    renderer->vtable->destroy(renderer);
    DataWin_free(dataWin);

    return 0;
}
