#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <stdio.h>
#include <malloc.h>
#include <dmaKit.h>
#include <gsKit.h>
#include <gsToolkit.h>
#include <gsFontM.h>
#include <libpad.h>
#include <libmc.h>
#include <libkbd.h>
#include <timer.h>
#include <unistd.h>
#include <sbv_patches.h>

#include "runner.h"
#include "runner_keyboard.h"
#include "vm.h"
#include "../data_win.h"
#include "../json_reader.h"
#include "ps2_file_system.h"
#ifndef DISABLE_PS2_AUDIO
#include "ps2_audio_system.h"
#endif
#include "gs_renderer.h"
#include "noop_audio_system.h"
#include "ps2_utils.h"
#include "stb_ds.h"
#include "utils.h"

#ifdef GPROF_PROFILING
#include <ps2prof.h>
#endif

// Embedded ps2sdk IRX modules (generated by bin2c at build time)
extern unsigned char sio2man_irx[];
extern unsigned int size_sio2man_irx;
extern unsigned char mcman_irx[];
extern unsigned int size_mcman_irx;
extern unsigned char mcserv_irx[];
extern unsigned int size_mcserv_irx;
extern unsigned char padman_irx[];
extern unsigned int size_padman_irx;
extern unsigned char usbd_irx[];
extern unsigned int size_usbd_irx;
extern unsigned char ps2kbd_irx[];
extern unsigned int size_ps2kbd_irx;
#ifndef DISABLE_PS2_AUDIO
extern unsigned char freesd_irx[];
extern unsigned int size_freesd_irx;
extern unsigned char audsrv_irx[];
extern unsigned int size_audsrv_irx;
#endif

// The maximum memory of a normal PS2 console
// Developer consoles may have more memory, but because ps2sdk does not have a way to know
// how much memory the console really has, we will use this value instead
static int MAX_MEMORY_BYTES = 33554432;

// 256-byte aligned buffer for libpad
static char padBuf[256] __attribute__((aligned(64)));

// Controller button to GML key mapping
typedef struct {
    uint16_t padButton;
    int32_t gmlKey;
} PadMapping;

static PadMapping* padMappings = nullptr;
static int padMappingCount = 0;

// Previous frame's button state for detecting press/release edges
static uint16_t prevButtons = 0xFFFF; // All buttons released (buttons are active-low)

// ===[ USB Keyboard ]===

static bool kbdAvailable = false;

// Shift modifier state (left-or-right).
static bool kbdShiftHeld = false;

// Map a USB HID usage code (as delivered by ps2kbd.irx in RAW mode) to a GML VK code.
static int32_t hidUsageToGmlKey(uint8_t hid) {
    // Letters: HID 0x04..0x1D -> ASCII 'A'..'Z' (GML uses uppercase ASCII)
    if (hid >= 0x04 && hid <= 0x1D) return (int32_t) ('A' + (hid - 0x04));
    // Numbers: HID 0x1E..0x26 -> '1'..'9', 0x27 -> '0'
    if (hid >= 0x1E && hid <= 0x26) return (int32_t) ('1' + (hid - 0x1E));
    if (hid == 0x27) return (int32_t) '0';
    // Special keys need mapping
    switch (hid) {
        case 0x28: return VK_ENTER;      // Enter
        case 0x29: return VK_ESCAPE;     // Escape
        case 0x2A: return VK_BACKSPACE;  // Backspace
        case 0x2B: return VK_TAB;        // Tab
        case 0x2C: return VK_SPACE;      // Space
        case 0x3A: return VK_F1;
        case 0x3B: return VK_F2;
        case 0x3C: return VK_F3;
        case 0x3D: return VK_F4;
        case 0x3E: return VK_F5;
        case 0x3F: return VK_F6;
        case 0x40: return VK_F7;
        case 0x41: return VK_F8;
        case 0x42: return VK_F9;
        case 0x43: return VK_F10;
        case 0x44: return VK_F11;
        case 0x45: return VK_F12;
        case 0x49: return VK_INSERT;
        case 0x4A: return VK_HOME;
        case 0x4B: return VK_PAGEUP;
        case 0x4C: return VK_DELETE;
        case 0x4D: return VK_END;
        case 0x4E: return VK_PAGEDOWN;
        case 0x4F: return VK_RIGHT;
        case 0x50: return VK_LEFT;
        case 0x51: return VK_DOWN;
        case 0x52: return VK_UP;
        case 0xE0: case 0xE4: return VK_CONTROL;  // Left/Right Ctrl
        case 0xE1: case 0xE5: return VK_SHIFT;    // Left/Right Shift
        case 0xE2: case 0xE6: return VK_ALT;      // Left/Right Alt
        default: return -1;
    }
}

// Translate a HID usage code to an ASCII character for RunnerKeyboard_onCharacter.
// Also handles when the shift key is held.
static unsigned int hidUsageToAsciiChar(uint8_t hid, bool shift) {
    // Letters A-Z: HID 0x04..0x1D
    if (hid >= 0x04 && hid <= 0x1D) {
        char base = (char) ('a' + (hid - 0x04));
        return (unsigned int) (shift ? (base - 32) : base);
    }

    // Digits / top-row symbols: 0x1E..0x26 -> 1..9, 0x27 -> 0
    static const char digitsUnshifted[10] = {'1','2','3','4','5','6','7','8','9','0'};
    static const char digitsShifted[10]   = {'!','@','#','$','%','^','&','*','(',')'};
    if (hid >= 0x1E && hid <= 0x26) return (unsigned int) (shift ? digitsShifted[hid - 0x1E] : digitsUnshifted[hid - 0x1E]);
    if (hid == 0x27) return (unsigned int) (shift ? digitsShifted[9] : digitsUnshifted[9]);

    switch (hid) {
        case 0x28: return (unsigned int) '\r';  // Enter
        case 0x2A: return (unsigned int) '\b';  // Backspace
        case 0x2B: return (unsigned int) '\t';  // Tab
        case 0x2C: return (unsigned int) ' ';   // Space
        case 0x2D: return (unsigned int) (shift ? '_' : '-');
        case 0x2E: return (unsigned int) (shift ? '+' : '=');
        case 0x2F: return (unsigned int) (shift ? '{' : '[');
        case 0x30: return (unsigned int) (shift ? '}' : ']');
        case 0x31: return (unsigned int) (shift ? '|' : '\\');
        case 0x33: return (unsigned int) (shift ? ':' : ';');
        case 0x34: return (unsigned int) (shift ? '"' : '\'');
        case 0x35: return (unsigned int) (shift ? '~' : '`');
        case 0x36: return (unsigned int) (shift ? '<' : ',');
        case 0x37: return (unsigned int) (shift ? '>' : '.');
        case 0x38: return (unsigned int) (shift ? '?' : '/');
        default: return 0;
    }
}

// ===[ Loading Screen ]===

// Maximum number of chunk stats we track (24 chunks in data.win, but only some have interesting counts)
#define MAX_CHUNK_STATS 24

typedef struct {
    char label[16];
    uint32_t count;
} ChunkStat;

typedef struct {
    GSGLOBAL* gsGlobal;
    GSFONTM* gsFontM;
    ChunkStat stats[MAX_CHUNK_STATS];
    int statCount;
} LoadingScreenState;

// Draws the bottom-left credits text (shared between status screen and loading screen)
static void drawCreditsText(GSGLOBAL* gs, GSFONTM* fontm) {
    u64 darkGray = GS_SETREG_RGBAQ(0x70, 0x70, 0x70, 0x80, 0x00);
    float creditsScale = 0.4f;
    float lineHeight = 26.0f * creditsScale;
    float creditsY = 448.0f - 10.0f - lineHeight * 2.0f;

    char versionText[128];
    snprintf(versionText, sizeof(versionText), "Butterscotch (%s) [%s]", BUTTERSCOTCH_COMMIT_HASH, BUTTERSCOTCH_COMMIT_DATE);
    gsKit_fontm_print_scaled(gs, fontm, 10.0f, creditsY, 1, creditsScale, darkGray, versionText);
    gsKit_fontm_print_scaled(gs, fontm, 10.0f, creditsY + lineHeight, 1, creditsScale, darkGray, "Created by MrPowerGamerBR (https://mrpowergamerbr.com/)");
}

// Draws a simple status screen with "Butterscotch" title, optional game name, and a status message (no progress bar)
// gameName can be nullptr if the game name is not yet known
// Begins a status screen: clears, draws title + optional game name, leaves center align active
static void beginStatusScreen(GSGLOBAL* gs, GSFONTM* fontm, const char* gameName) {
    gsKit_clear(gs, GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x80, 0x00));

    u64 title = GS_SETREG_RGBAQ(0x5E, 0x54, 0x92, 0x80, 0x00);
    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);

    fontm->Align = GSKIT_FALIGN_CENTER;
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, 180.0f, 1, 0.8f, title, "Butterscotch");
    if (gameName) {
        gsKit_fontm_print_scaled(gs, fontm, 320.0f, 210.0f, 1, 0.5f, gray, gameName);
    }
}

// Ends a status screen: draws credits, resets align, flips
static void endStatusScreen(GSGLOBAL* gs, GSFONTM* fontm) {
    fontm->Align = GSKIT_FALIGN_LEFT;
    drawCreditsText(gs, fontm);
    gsKit_queue_exec(gs);
    gsKit_sync_flip(gs);
}

// Draws chunk item counts in the top-left corner (if any stats have been recorded)
static void drawChunkStats(GSGLOBAL* gs, GSFONTM* fontm, LoadingScreenState* loadingState) {
    if (!loadingState || loadingState->statCount == 0)
        return;

    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);
    fontm->Align = GSKIT_FALIGN_LEFT;
    float statsY = 10.0f;
    float statsScale = 0.35f;
    float statsLineHeight = 14.0f;
    char statLine[32];

    repeat(loadingState->statCount, i) {
        snprintf(statLine, sizeof(statLine), "%d %s", loadingState->stats[i].count, loadingState->stats[i].label);
        gsKit_fontm_print_scaled(gs, fontm, 10.0f, statsY, 1, statsScale, gray, statLine);
        statsY += statsLineHeight;
    }
}

static void drawStatusScreen(GSGLOBAL* gs, GSFONTM* fontm, const char* gameName, const char* statusText, LoadingScreenState* loadingState) {
    beginStatusScreen(gs, fontm, gameName);
    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, 300.0f, 1, 0.5f, gray, statusText);
    drawChunkStats(gs, fontm, loadingState);
    endStatusScreen(gs, fontm);
}

static void loadingScreenCallback(const char* chunkName, int chunkIndex, int totalChunks, DataWin* dataWin, void* userData) {
    LoadingScreenState* state = (LoadingScreenState*) userData;
    GSGLOBAL* gs = state->gsGlobal;
    GSFONTM* fontm = state->gsFontM;

    const char* gameName = dataWin->gen8.displayName ? dataWin->gen8.displayName : "Unknown Game";
    beginStatusScreen(gs, fontm, gameName);

    // Loading bar
    u64 white = GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00);
    u64 barBg = GS_SETREG_RGBAQ(0x40, 0x40, 0x40, 0x80, 0x00);
    u64 barFg = GS_SETREG_RGBAQ(0xFF, 0xCC, 0x00, 0x80, 0x00); // Butterscotch yellow

    float barX = 120.0f;
    float barY = 300.0f;
    float barW = 400.0f;
    float barH = 20.0f;
    float progress = (float) (chunkIndex + 1) / (float) totalChunks;

    // Bar background (dark gray)
    gsKit_prim_sprite(gs, barX, barY, barX + barW, barY + barH, 1, barBg);

    // Bar fill (butterscotch yellow)
    float fillW = barW * progress;
    if (fillW > 1.0f) {
        gsKit_prim_sprite(gs, barX, barY, barX + fillW, barY + barH, 1, barFg);
    }

    // Enable alpha blending so the font text doesn't have a black box behind it
    gs->PrimAlphaEnable = GS_SETTING_ON;
    gsKit_set_primalpha(gs, GS_SETREG_ALPHA(0, 1, 0, 1, 0), 0);

    // Percentage text centered on the bar
    char percentText[8];
    snprintf(percentText, sizeof(percentText), "%d%%", (int) (progress * 100));
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, barY + 4.5f, 1, 0.4f, white, percentText);

    // Chunk name text below the bar
    char statusText[32];
    snprintf(statusText, sizeof(statusText), "Loading %.4s... (%d/%d)", chunkName, chunkIndex + 1, totalChunks);
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, barY + barH + 10.0f, 1, 0.5f, white, statusText);

    // Memory usage below the status text
    u64 gray = GS_SETREG_RGBAQ(0xAA, 0xAA, 0xAA, 0x80, 0x00);
    void* heapTop = sbrk(0);
    int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
    char memText[48];
    snprintf(memText, sizeof(memText), "Memory: %.1f/%.1f MB", usedBytes / (1024.0f * 1024.0f), MAX_MEMORY_BYTES / (1024.0f * 1024.0f));
    gsKit_fontm_print_scaled(gs, fontm, 320.0f, barY + barH + 30.0f, 1, 0.4f, gray, memText);

    // Record item counts for already-parsed chunks (callback fires before parsing, so we scan all counts each time and add any newly non-zero ones in the order they appear)
    typedef struct { uint32_t* countPtr; const char* label; } CountSource;
    CountSource sources[] = {
        { &dataWin->sond.count, "sounds" },
        { &dataWin->sprt.count, "sprites" },
        { &dataWin->bgnd.count, "backgrounds" },
        { &dataWin->font.count, "fonts" },
        { &dataWin->objt.count, "objects" },
        { &dataWin->room.count, "rooms" },
        { &dataWin->code.count, "code entries" },
        { &dataWin->txtr.count, "textures" },
    };

    // sizeof(sources) = size of the ENTIRE array
    // So, if we divide the size of the ENTIRE array by the size of a SINGLE entry, we get the number of entries
    int arrayLength = sizeof(sources) / sizeof(CountSource);

    repeat(arrayLength, i) {
        if (*sources[i].countPtr == 0)
            continue;

        // Check if we already recorded this label
        bool found = false;
        forEach(CountSource, stat, sources, state->statCount) {
            if (strcmp(stat->label, sources[i].label) == 0) {
                found = true;
                break;
            }
        }

        if (!found && MAX_CHUNK_STATS > state->statCount) {
            ChunkStat* stat = &state->stats[state->statCount++];
            snprintf(stat->label, sizeof(stat->label), "%s", sources[i].label);
            stat->count = *sources[i].countPtr;
        }
    }

    drawChunkStats(gs, fontm, state);

    gs->PrimAlphaEnable = GS_SETTING_OFF;

    endStatusScreen(gs, fontm);
}

int main(int argc, char* argv[]) {
    SifInitRpc(0);
    sbv_patch_enable_lmb();

    PS2Utils_extractDeviceKey(argv[0]);

    fprintf(stderr, "argv0 is %s, device key is %s\n", argv[0], deviceKey.key);

    PS2Utils_loadFSDrivers();

    fprintf(stderr, "Loaded FS drivers!\n");

    const char* dataWinPath = PS2Utils_createDevicePath("DATA.WIN");

    printf("Butterscotch PS2 - Loading %s\n", dataWinPath);

    // ===[ Initialize gsKit ]===
    // This must happen first so we can show the loading screen during other init steps
    GSGLOBAL* gsGlobal = gsKit_init_global();
    gsGlobal->Mode = GS_MODE_NTSC;
    gsGlobal->Interlace = GS_INTERLACED;
    gsGlobal->Field = GS_FIELD;
    gsGlobal->Width = 640;
    gsGlobal->Height = 448;
    gsGlobal->PSM = GS_PSM_CT16;
    gsGlobal->PSMZ = GS_PSMZ_16;
    gsGlobal->DoubleBuffering = GS_SETTING_ON;
    gsGlobal->ZBuffering = GS_SETTING_OFF;

    gsGlobal->PrimAAEnable = GS_SETTING_OFF;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC, D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gsKit_init_screen(gsGlobal);
    // Use ONE SHOT mode
    gsKit_mode_switch(gsGlobal, GS_ONESHOT);

    // ===[ Initialize FONTM (ROM font) for debug overlay ]===
    GSFONTM* gsFontM = gsKit_init_fontm();
    gsKit_fontm_upload(gsGlobal, gsFontM);
    gsFontM->Spacing = 0.95f;

    // ===[ Initialize Controller ]===
    drawStatusScreen(gsGlobal, gsFontM, nullptr, "Initializing controller...", nullptr);

    int ret;
    ret = SifExecModuleBuffer(sio2man_irx, size_sio2man_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load sio2man: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(mcman_irx, size_mcman_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load mcman: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(mcserv_irx, size_mcserv_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load mcserv: %d\n", ret);
        return 1;
    }
    ret = mcInit(MC_TYPE_MC);
    if (0 > ret) {
        printf("Failed to init libmc: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(padman_irx, size_padman_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load padman: %d\n", ret);
        return 1;
    }

    padInit(0);
    padPortOpen(0, 0, padBuf);

    // ===[ Load USB Keyboard IOP Modules ]===
    int usbdRet = SifExecModuleBuffer(usbd_irx, size_usbd_irx, 0, nullptr, nullptr);
    if (0 > usbdRet) {
        printf("Warning: failed to load usbd: %d (keyboard disabled)\n", usbdRet);
    } else {
        int kbdRet = SifExecModuleBuffer(ps2kbd_irx, size_ps2kbd_irx, 0, nullptr, nullptr);
        if (0 > kbdRet) {
            printf("Warning: failed to load ps2kbd: %d (keyboard disabled)\n", kbdRet);
        } else if (PS2KbdInit() == 0) {
            printf("Warning: PS2KbdInit failed (keyboard disabled)\n");
        } else {
            PS2KbdSetReadmode(PS2KBD_READMODE_RAW);
            PS2KbdSetBlockingMode(PS2KBD_NONBLOCKING);
            kbdAvailable = true;
            printf("USB keyboard initialized\n");
        }
    }

#ifndef DISABLE_PS2_AUDIO
    // ===[ Load Audio IOP Modules ]===
    ret = SifExecModuleBuffer(freesd_irx, size_freesd_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load freesd: %d\n", ret);
    }
    ret = SifExecModuleBuffer(audsrv_irx, size_audsrv_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load audsrv: %d\n", ret);
    }
#endif

    // Wait for pad to be ready
    drawStatusScreen(gsGlobal, gsFontM, nullptr, "Waiting for controller...", nullptr);

    int padState;
    do {
        padState = padGetState(0, 0);
    } while (PAD_STATE_STABLE != padState && PAD_STATE_FINDCTP1 != padState);

    printf("Controller initialized\n");

    // ===[ Loading Screen State ]===
    LoadingScreenState loadingState = {
        .gsGlobal = gsGlobal,
        .gsFontM = gsFontM,
    };

    // ===[ Load CONFIG.JSN ]===
    drawStatusScreen(gsGlobal, gsFontM, nullptr, "Loading CONFIG.JSN...", nullptr);

    char* configJsonPath = PS2Utils_createDevicePath("CONFIG.JSN");
    FILE* configFile = fopen(configJsonPath, "rb");
    JsonValue* configRoot = nullptr;

    if (configFile != nullptr) {
        fseek(configFile, 0, SEEK_END);
        long configSize = ftell(configFile);
        fseek(configFile, 0, SEEK_SET);

        char* configJsonText = safeMalloc((size_t) configSize + 1);
        size_t configBytesRead = fread(configJsonText, 1, (size_t) configSize, configFile);
        configJsonText[configBytesRead] = '\0';
        fclose(configFile);

        configRoot = JsonReader_parse(configJsonText);
        free(configJsonText);
    }
    free(configJsonPath);

    if (configRoot == nullptr) {
        drawStatusScreen(gsGlobal, gsFontM, nullptr, "CONFIG.JSN invalid or not found!", nullptr);
        while (true) {}
    }

    bool lazyLoadRooms = JsonReader_getBool(JsonReader_getObject(configRoot, "lazyLoadRooms"));
    StringBooleanEntry* eagerRooms = nullptr; // stb_ds string-keyed set; keys borrowed from configRoot
    JsonValue* eagerArr = JsonReader_getObject(configRoot, "eagerlyLoadedRooms");
    int n = JsonReader_arrayLength(eagerArr);
    repeat(n, i) {
        const char* name = JsonReader_getString(JsonReader_getArrayElement(eagerArr, i));
        if (name != nullptr) shput(eagerRooms, (char*) name, true);
    }

    // ===[ Parse data.win ]===
    drawStatusScreen(gsGlobal, gsFontM, nullptr, "Loading data.win...", nullptr);

    DataWin* dataWin = DataWin_parse(
        dataWinPath,
        (DataWinParserOptions) {
            .parseGen8 = true,
            .parseOptn = true,
            .parseLang = true,
            .parseExtn = true,
            .parseSond = true,
            .parseAgrp = true,
            .parseSprt = true,
            .parseBgnd = true,
            .parsePath = true,
            .parseScpt = true,
            .parseGlob = true,
            .parseShdr = true,
            .parseFont = true,
            .parseTmln = true,
            .parseObjt = true,
            .parseRoom = true,
            .parseTpag = true,
            .parseCode = true,
            .parseVari = true,
            .parseFunc = true,
            .parseStrg = true,
            .parseTxtr = false,
            .parseAudo = false,
            .skipLoadingPreciseMasksForNonPreciseSprites = true,
            .lazyLoadRooms = lazyLoadRooms,
            .eagerlyLoadedRooms = eagerRooms,
            .progressCallback = loadingScreenCallback,
            .progressCallbackUserData = &loadingState,
        }
    );
    free(dataWinPath);
    shfree(eagerRooms);

    {
        void* heapTop = sbrk(0);
        int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
        int32_t freeBytes = MAX_MEMORY_BYTES - usedBytes;
        printf("Memory after data.win parsing: used=%d bytes (%.1f KB), total=%d bytes (%.1f KB), free=%d bytes (%.1f KB)\n", usedBytes, usedBytes / 1024.0f, MAX_MEMORY_BYTES, MAX_MEMORY_BYTES / 1024.0f, freeBytes, freeBytes / 1024.0f);
    }

    FileSystem* fileSystem = Ps2FileSystem_create(configRoot, dataWin->gen8.displayName);
    if (fileSystem == nullptr) {
        drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "CONFIG.JSN is missing the fileSystem configuration!", &loadingState);
        while (true) {}
    }

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Creating VM...", &loadingState);

    VMContext* vm = VM_create(dataWin);

    // ===[ Initialize Renderer ]===
    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Initializing renderer...", &loadingState);

    Renderer* renderer = GsRenderer_create(gsGlobal);

    // ===[ Initialize Audio System ]===
#ifndef DISABLE_PS2_AUDIO
    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Initializing audio...", &loadingState);
    Ps2AudioSystem* ps2Audio = Ps2AudioSystem_create();
    AudioSystem* audioSystem = (AudioSystem*) ps2Audio;
#else
    AudioSystem* audioSystem = (AudioSystem*) NoopAudioSystem_create();
#endif

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Creating runner...", &loadingState);

    Runner* runner = Runner_create(dataWin, vm, renderer, fileSystem, audioSystem);

    // Parse disabledObjects from CONFIG.JSN
    JsonValue* disabledObjectsArr = JsonReader_getObject(configRoot, "disabledObjects");
    if (disabledObjectsArr != nullptr && JsonReader_isArray(disabledObjectsArr)) {
        sh_new_strdup(runner->disabledObjects);
        int disabledCount = JsonReader_arrayLength(disabledObjectsArr);
        repeat(disabledCount, i) {
            JsonValue* elem = JsonReader_getArrayElement(disabledObjectsArr, i);
            if (elem != nullptr && JsonReader_isString(elem)) {
                const char* objName = JsonReader_getString(elem);
                shput(runner->disabledObjects, objName, 1);
                printf("Disabled object: %s\n", objName);
            }
        }
    }

    // Parse controllerMappings from CONFIG.JSN
    JsonValue* controllerMappingsObj = JsonReader_getObject(configRoot, "controllerMappings");
    if (controllerMappingsObj != nullptr && JsonReader_isObject(controllerMappingsObj)) {
        padMappingCount = JsonReader_objectLength(controllerMappingsObj);
        padMappings = safeMalloc(sizeof(PadMapping) * padMappingCount);
        repeat(padMappingCount, i) {
            const char* padButtonStr = JsonReader_getObjectKey(controllerMappingsObj, i);
            JsonValue* gmlKeyVal = JsonReader_getObjectValue(controllerMappingsObj, i);
            padMappings[i].padButton = (uint16_t) atoi(padButtonStr);
            padMappings[i].gmlKey = (int32_t) JsonReader_getInt(gmlKeyVal);
            printf("CONFIG.JSN: controllerMapping pad=%d -> gmlKey=%d\n", padMappings[i].padButton, padMappings[i].gmlKey);
        }
    }

    {
        void* heapTop = sbrk(0);
        int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
        int32_t freeBytes = MAX_MEMORY_BYTES - usedBytes;
        printf("Memory after VM and runner creation: used=%d bytes (%.1f KB), total=%d bytes (%.1f KB), free=%d bytes (%.1f KB)\n", usedBytes, usedBytes / 1024.0f, MAX_MEMORY_BYTES, MAX_MEMORY_BYTES / 1024.0f, freeBytes, freeBytes / 1024.0f);
    }

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Initializing first room...", &loadingState);
    Runner_initFirstRoom(runner);

    drawStatusScreen(gsGlobal, gsFontM, dataWin->gen8.displayName, "Reticulating splines...", &loadingState);

    // ===[ gprof Profiler Setup ]===
#ifdef GPROF_PROFILING
    // Reset profiler to ignore any data collected during the initialization steps
    gprof_stop(nullptr, 0);

    // If not running from host:, load USB mass storage drivers so we can write gmon.out to mass:
    if (strcmp(deviceKey.key, "host") != 0)
        PS2Utils_loadMassStorageDrivers();

    gprof_start();
    fprintf(stderr, "gprof: Profiling started!\n");
#endif

    Gen8* gen8 = &dataWin->gen8;
    int32_t gameW = (int32_t) gen8->defaultWindowWidth;
    int32_t gameH = (int32_t) gen8->defaultWindowHeight;

    // ===[ Initialize Timer ]===
    InitTimer(kBUSCLK);
    StartTimerSystemTime();

    // ===[ Main Loop ]===
    bool debugOverlayEnabled = JsonReader_getBool(JsonReader_getObject(configRoot, "debugOverlayEnabled"));
    while (!runner->shouldExit) {
        u64 frameStartTime = GetTimerSystemTime();
        // ===[ Poll Controller (always poll every vsync) ]===
        // NOTE: We do NOT call RunnerKeyboard_beginFrame here! Pressed/released edges accumulate across vsyncs so that quick taps on non-game-frame
        // vsyncs are not lost
        //
        // beginFrame is called after the game consumes input.

        struct padButtonStatus padStatus;
        unsigned char padResult = padRead(0, 0, &padStatus);
        uint16_t buttons = 0xFFFF; // all released by default
        if (padResult != 0) {
            buttons = padStatus.btns;

            repeat(padMappingCount, i) {
                uint16_t mask = padMappings[i].padButton;
                int32_t gmlKey = padMappings[i].gmlKey;

                // PS2 buttons are active-low: 0 = pressed, 1 = released
                bool wasPressed = (prevButtons & mask) == 0;
                bool isPressed = (buttons & mask) == 0;

                if (isPressed && !wasPressed) {
                    RunnerKeyboard_onKeyDown(runner->keyboard, gmlKey);
                } else if (!isPressed && wasPressed) {
                    RunnerKeyboard_onKeyUp(runner->keyboard, gmlKey);
                }
            }

            prevButtons = buttons;
        }

        // ===[ Poll USB Keyboard ]===
        // Drain all pending RAW events this vsync so press/release edges aren't dropped.
        if (kbdAvailable) {
            PS2KbdRawKey rawKey;
            while (PS2KbdReadRaw(&rawKey) > 0) {
                int32_t gmlKey = hidUsageToGmlKey(rawKey.key);

                // Track shift modifier locally so we can pick the correct glyph for onCharacter.
                if (rawKey.key == 0xE1 || rawKey.key == 0xE5) {
                    kbdShiftHeld = (rawKey.state == PS2KBD_RAWKEY_DOWN);
                }

                if (rawKey.state == PS2KBD_RAWKEY_DOWN) {
                    if (gmlKey >= 0) RunnerKeyboard_onKeyDown(runner->keyboard, gmlKey);
                    unsigned int ch = hidUsageToAsciiChar(rawKey.key, kbdShiftHeld);
                    if (ch != 0) RunnerKeyboard_onCharacter(runner->keyboard, ch);
                } else if (rawKey.state == PS2KBD_RAWKEY_UP) {
                    if (gmlKey >= 0) RunnerKeyboard_onKeyUp(runner->keyboard, gmlKey);
                }
            }
        }

        // R2 removes speed cap (ignore waiting for vsync)
        bool speedCapRemoved = (padResult != 0) && ((buttons & PAD_R2) == 0);

        // Go to next room
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_PAGEUP)) {
            DataWin* dw = runner->dataWin;
            if ((int32_t) dw->gen8.roomOrderCount > runner->currentRoomOrderPosition + 1) {
                int32_t nextIdx = dw->gen8.roomOrder[runner->currentRoomOrderPosition + 1];
                runner->pendingRoom = nextIdx;
                runner->audioSystem->vtable->stopAll(runner->audioSystem);
                fprintf(stderr, "Debug: Going to next room -> %s\n", dw->room.rooms[nextIdx].name);
            }
        }

        // Go to previous room
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_PAGEDOWN)) {
            DataWin* dw = runner->dataWin;
            forEachIndexed(Room, room, i, dw->room.rooms, dw->room.count) {
                if (strcmp(room->name, "room_asrielappears") == 0) {
                    runner->pendingRoom = i;
                    runner->audioSystem->vtable->stopAll(runner->audioSystem);
                    break;
                }
            }
        }

        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_F12)) {
            debugOverlayEnabled = !debugOverlayEnabled;
        }

        // Reset global interact state because I HATE when I get stuck while moving through rooms
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_F10)) {
            int32_t interactVarId = shget(runner->vmContext->globalVarNameMap, "interact");

            runner->vmContext->globalVars[interactVarId] = RValue_makeInt32(0);
            printf("Changed global.interact [%d] value!\n", interactVarId);
        }

        // ===[ Game Logic ]===
        uint32_t roomSpeed = runner->currentRoom->speed;

        Runner_step(runner);

        gsKit_clear(gsGlobal, GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x80, 0x00));

        renderer->vtable->beginFrame(renderer, gameW, gameH, 640, 448);

        // Clear with room background color
        if (runner->drawBackgroundColor) {
            uint8_t bgR = BGR_R(runner->backgroundColor);
            uint8_t bgG = BGR_G(runner->backgroundColor);
            uint8_t bgB = BGR_B(runner->backgroundColor);
            u64 bgColor = GS_SETREG_RGBAQ(bgR, bgG, bgB, 0x80, 0x00);
            gsKit_prim_sprite(gsGlobal, 0, 0, 640, 448, 0, bgColor);
        }

        // Render views
        Room* activeRoom = runner->currentRoom;
        bool anyViewRendered = false;

        bool viewsEnabled = (activeRoom->flags & 1) != 0;

        if (viewsEnabled) {
            repeat(8, vi) {
                if (!activeRoom->views[vi].enabled) continue;

                int32_t viewX = activeRoom->views[vi].viewX;
                int32_t viewY = activeRoom->views[vi].viewY;
                int32_t viewW = activeRoom->views[vi].viewWidth;
                int32_t viewH = activeRoom->views[vi].viewHeight;
                int32_t portX = activeRoom->views[vi].portX;
                int32_t portY = activeRoom->views[vi].portY;
                int32_t portW = activeRoom->views[vi].portWidth;
                int32_t portH = activeRoom->views[vi].portHeight;
                float viewAngle = runner->viewAngles[vi];

                runner->viewCurrent = (int32_t) vi;
                renderer->vtable->beginView(renderer, viewX, viewY, viewW, viewH, portX, portY, portW, portH, viewAngle);

                Runner_draw(runner);

                renderer->vtable->endView(renderer);

                int32_t guiW = runner->guiWidth > 0 ? runner->guiWidth : portW;
                int32_t guiH = runner->guiHeight > 0 ? runner->guiHeight : portH;
                renderer->vtable->beginGUI(renderer, guiW, guiH, portX, portY, portW, portH);
                Runner_drawGUI(runner);
                renderer->vtable->endGUI(renderer);

                anyViewRendered = true;
            }
        }

        if (!anyViewRendered) {
            // No views enabled: render with default full-screen view
            runner->viewCurrent = 0;
            renderer->vtable->beginView(renderer, 0, 0, gameW, gameH, 0, 0, gameW, gameH, 0.0f);
            Runner_draw(runner);
            renderer->vtable->endView(renderer);

            int32_t guiW = runner->guiWidth > 0 ? runner->guiWidth : gameW;
            int32_t guiH = runner->guiHeight > 0 ? runner->guiHeight : gameH;
            renderer->vtable->beginGUI(renderer, guiW, guiH, 0, 0, gameW, gameH);
            Runner_drawGUI(runner);
            renderer->vtable->endGUI(renderer);
        }

        runner->viewCurrent = 0;

        renderer->vtable->endFrame(renderer);

        // Clear pressed/released edges after both Step and Draw have consumed input
        // This MUST be after Runner_draw because games CAN handle input in Draw events (e.g. Undertale's naming screen)
        RunnerKeyboard_beginFrame(runner->keyboard);

        // Update audio system (gain fading, stream to audsrv)
        float dt = 1.0f / (float) roomSpeed;
        if (0.0f > dt) dt = 0.0f;
        if (dt > 0.1f) dt = 0.1f;
        runner->audioSystem->vtable->update(runner->audioSystem, dt);

        u64 runnerEndTime = GetTimerSystemTime();
        u64 duration = runnerEndTime - frameStartTime;
        float tickTime = (float) duration / (float) (kBUSCLK / 1000);

        // ===[ Debug Overlay ]===
        if (debugOverlayEnabled) {
            u64 debugColor = GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00);
            // sbrk(0) returns the actual heap frontier; true free = top of RAM - sbrk frontier
            void* heapTop = sbrk(0);
            int32_t freeBytes = MAX_MEMORY_BYTES - (int32_t) (uintptr_t) heapTop;

            char debugText[256];
            uint32_t vramFreeBytes = GS_VRAM_SIZE - gsGlobal->CurrentPointer;

            // Count atlases loaded in VRAM and EE RAM cache
            GsRenderer* gsRenderer = (GsRenderer*) renderer;
            uint32_t vramAtlasCount = 0;
            uint32_t eeramAtlasCount = 0;
            repeat(gsRenderer->atlasCount, ai) {
                if (gsRenderer->atlasToChunk[ai] >= 0) vramAtlasCount++;
                if (gsRenderer->eeCacheEntries[ai].atlasId >= 0) eeramAtlasCount++;
            }

            snprintf(debugText, sizeof(debugText), "Tick: %.2fms\nFree: %d bytes\nVRAM Free: %lu bytes\nRoom Speed: %u%s\nAtlas: (%u, %u, %u)%s", tickTime, freeBytes, (unsigned long) vramFreeBytes, roomSpeed, speedCapRemoved ? " [UNCAPPED]" : "", vramAtlasCount, eeramAtlasCount, gsRenderer->atlasCount, gsRenderer->evictedAtlasUsedInCurrentFrame ? " [THRASHING]" : "");
            gsKit_fontm_print_scaled(gsGlobal, gsFontM, 10.0f, 10.0f, 10, 0.6f, debugColor, debugText);
        }

        // Execute draw queue and flip buffers
        gsKit_queue_exec(gsGlobal);
        gsKit_sync_flip(gsGlobal);

        // Busy-wait until enough time has elapsed for this frame if needed
        if (!speedCapRemoved && roomSpeed > 0) {
            u64 targetTicks = kBUSCLK / roomSpeed;
            while (targetTicks > GetTimerSystemTime() - frameStartTime) {
                // spin spin spin!
            }
        }
    }

    // ===[ gprof Profiler Output ]===
#ifdef GPROF_PROFILING
    {
        const char* gprofPath;
        if (strcmp(deviceKey.key, "host") == 0) {
            gprofPath = "host:gmon.out";
        } else {
            gprofPath = "mass:gmon.out";
        }
        fprintf(stderr, "gprof: Writing profiling data to %s\n", gprofPath);
        gprof_stop(gprofPath, 1);
        fprintf(stderr, "gprof: Done\n");
    }
#endif

    // For some god awful reason PCSX2 crashes when destroying the audio system (???)
    // runner->audioSystem->vtable->destroy(runner->audioSystem);
    runner->audioSystem = nullptr;
    renderer->vtable->destroy(renderer);
    DataWin_free(dataWin);

    return 0;
}
